language: node_js
node_js:
- 8.12.0
cache:
  directories:
  - node_modules
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_2c82ee9ea59e_key -iv $encrypted_2c82ee9ea59e_iv
  -in travis.enc -out ~/.ssh/travis -d
- chmod 600 ~/.ssh/travis
- echo -e "Host 101.200.47.112\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm run test
after_script:
- scp -o stricthostkeychecking=no  -r ./public/* root@101.200.47.112:/usr/travis
branches:
  only:
  - master
env:
  global: 
